logging.level.org.springframework.boot.autoconfigure: ERROR
#数据库
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/book_store?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
#关闭thymeleaf缓存
  thymeleaf:
    cache: false
#  开启热部署
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
    freemarker:
      cache: false    #页面不加载缓存，修改即时生效
      #配置redis
  redis:
    host: 192.168.1.103
    port: 6379
    password: 123456






mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kuang.book.entiy



