logging.level.org.springframework.boot.autoconfigure: ERROR
#数据库
spring:
  datasource:
    username: root
    password: 991220

    hikari:
      max-lifetime: 300000
    url: jdbc:mysql://47.96.153.180:3306/book_store?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
#关闭thymeleaf缓存
  thymeleaf:
    cache: false
#  开启热部署
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
    freemarker:
      cache: false    #页面不加载缓存，修改即时生效
      #配置redis
  redis:
    host: 47.96.153.180
    port: 6379
    password: 991220



  mvc:
    static-path-pattern=/book/static/**:



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kuang.book.entiy


server:
  servlet:
    context-path: /book

