logging.level.org.springframework.boot.autoconfigure: ERROR
spring:
  application:
    name: cloud-payment-service
  datasource:
    username: root
    password: 123456

    hikari:
      max-lifetime: 300000
    url: jdbc:mysql://127.0.0.1/pay?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

#让payment8001注入eureka集群
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

#  设置eureka显示的名称和ip地址
  instance:
    instance-id: payment8001
    prefer-ip-address: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.leng.springcloud.enties
server:
  port: 8001
